### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Varstahl** [Drahsid/ResizableHUD#2]
After #1 I don't wanna be that guy, and I wish I could help but I'm extremely new to FF14 plugins. There are two problems atm, even after update v1.0.0.14836:
1. UI is completely ineffective
   ![image](https://user-images.githubusercontent.com/284077/212544442-55a1098d-8493-4cbf-b245-ffce0d896253.png)
   I can set any scale or position that I want and save, it does absolutely nothing at all.
2. From command line it's even worse. If I run the command `/prhudpos <component> x N` it starts throwing a bunch of errors in the logs, then even if I'm changing position it logs out `Scaled.`, followed by another error:
   ![image](https://user-images.githubusercontent.com/284077/212544532-b88bd684-d54e-4b05-8b91-48cfbce61569.png)
   Disregard the first X/Y, that's clearly my error. The ResizableHUD parameters update correctly, but nothing changes.

I've tried with different components, restarting FF14, entering and exiting HUD Layout mode, but nothing worked so far. I'd like to help if I can, but I just don't know where to start. Also I tried using `/xllog` but absolutely nothing is shown, not in verbose, debug or anything else.

Also, unrelated to this issue, but while I'm at it, the help gives the wrong commands:
![image](https://user-images.githubusercontent.com/284077/212544705-568a4534-c58c-420a-82bc-b8d443ba0e4c.png)
It makes it seem like `/prhudpos` and `/prhud pos` are aliases, while the latter just opens/closes the Resizable HUD window.

**Comment by Drahsid** [comment]
Hey, sorry about that,  you must have gotten the plugin while I was still working on stuff. Try updating to the latest and let me know how it goes.

**Comment by Varstahl** [comment]
Ah, no worries, I tried to update but it was probably cached

And yes it works, as I noticed from the fact that every action bar suddenly moved to the top of the screen :D

**Comment by Varstahl** [comment]
Sorry to reopen this, I forgot to test from the command line.
![image](https://user-images.githubusercontent.com/284077/212568007-b34b4c2c-bfba-4422-bd7e-f6ccf05142e1.png)
The problem with the commands still stand, if you try to alter the position you get the errors, the "Scaled." message, and nothing happens.

Scaling works, although I noticed that possibly due to locale, even if it's `1.5` in the UI I need to write `1,5` or it gets interpreted as `1500`. Weird, might be a C# quirk due to the numbers formatting rules for my country.

**Comment by Drahsid** [comment]
Did you do `/prhudadd _ActionBar05` before running `prhudpos` ?
Looks like the error output is just a regression in the logic of the command that happened when I refactored the command code.

**Comment by Drahsid** [comment]
I have updated the plugin on my repo with a fix, see if that works.

**Comment by Varstahl** [comment]
Uhm, the error messages are gone although `0.296` still gets interpreted as 296, the position says "Moved.", but the UI doesn't update and the element remains where it was.

After the command the controls flicker, as if "updating", but the position remains the same so they just reappear with no positional changes. ~~May it be because I'm in relative mode?~~ appears not to be the case, even in absolute it doesn't change position.

**Comment by Drahsid** [comment]
The `0.296` vs `0,296` thing may be a localization feature of .net, since I am simply using `float.Parse` to parse the input. There might be a bug with it when using relative mode, since the command only adjusts the absolute position value, and relative mode recalculates the absolute position every frame.

**Comment by Varstahl** [comment]
That's what I thought, so I disabled the relative and gave it absolute number of pixels, still doesn't update

**Comment by Drahsid** [comment]
Should be good now, see how it goes when you get the chance.

**Comment by Varstahl** [comment]
Yes! And yes, as you expected since the relative mode updates the absolute, the command doesn't work in relative, but yes now everything works :)

Sorry for being such a pest :D
